spring:
  datasource:
    url: jdbc:h2:mem:youlearndays-testcontainers-demo;MODE=PostgreSQL
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/dev

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql: TRACE
